Use retry watches
cloudogu/k8s-ces-setup pull request #114
Opened 2024-11-14 06:24 UTC by nhinze23

Resolves #113

2024-11-18 09:40 UTC, jelemux requested changes
Please resolve the conflicts.

You also wanted to update the ~~registry-lib or something along those lines~~ retry-lib if I remember correctly.

2024-11-18 10:18 UTC, jelemux requested changes

2024-11-18 10:18 UTC, jelemux commented on app/setup/component/waitForComponentStep_test.go
> +	t.Run("should not retry if the resource version is to old", func(t *testing.T) {
```suggestion
	t.Run("should not retry if the resource version is too old", func(t *testing.T) {
```

2024-11-18 10:18 UTC, jelemux commented on app/setup/dogus/waitForDoguStep.go
> +	_, err = retrywatch.Until(ctx, get.ResourceVersion, watcher, watcher.checkDoguStatus)
Same here with get vs. list

2024-11-18 10:18 UTC, jelemux commented on app/setup/component/waitForComponentStep.go
> +func NewWaitForComponentStep(client componentsClient, componentName string, namespace string) *waitForComponentStep {
Why is there a timeout for dogus, but not components?

2024-11-18 10:18 UTC, jelemux commented on app/setup/dogus/waitForDoguStep_test.go
> +	t.Run("should not retry if the resource version is to old", func(t *testing.T) {
```suggestion
	t.Run("should not retry if the resource version is too old", func(t *testing.T) {
```

2024-11-18 10:31 UTC, jelemux commented on app/setup/dogus/waitForDoguStep.go
> +	err := retry.OnErrorWithLimit(waitLimit, errors.IsNotFound, func() error {
Should we really wait an hour for that if our default timeout for the step is 5 minutes?

2024-11-18 10:31 UTC, jelemux commented on app/setup/component/waitForComponentStep.go
> +	err := retry.OnErrorWithLimit(waitLimit, errors.IsNotFound, func() error {
Same here, should we really wait an hour for that?

2024-11-18 11:59 UTC, nhinze23 commented on app/setup/component/waitForComponentStep.go
> +	_, err = retrywatch.Until(ctx, get.ResourceVersion, watcher, watcher.checkComponentStatus)
Yeah i thought this too and was a little bit confused:
The implementation of the retry watcher uses after every upcoming event the resourceVersion from the event objects. Which correspond to the resourceVersion from the components crs.

2024-11-18 12:05 UTC, nhinze23 commented on app/setup/dogus/waitForDoguStep.go
> +	err := retry.OnErrorWithLimit(waitLimit, errors.IsNotFound, func() error {
Oh i overlooked the timeout. We can just use it for the retry

2024-11-18 12:12 UTC, nhinze23 commented on app/setup/component/waitForComponentStep.go
> +func NewWaitForComponentStep(client componentsClient, componentName string, namespace string) *waitForComponentStep {
I don't know. I can implement it in the same way :+1:

2024-11-18 12:31 UTC, jelemux commented on app/setup/component/waitForComponentStep.go
> +	_, err = retrywatch.Until(ctx, get.ResourceVersion, watcher, watcher.checkComponentStatus)
Ok, if it works, this can stay the way it is.

2024-11-18 12:32 UTC, jelemux commented on app/setup/dogus/waitForDoguStep.go
> +	err := retry.OnErrorWithLimit(waitLimit, errors.IsNotFound, func() error {
Nice, we'll do it like that, then!

2024-11-18 12:34 UTC, jelemux commented on app/setup/component/waitForComponentStep.go
> +	err := retry.OnErrorWithLimit(waitLimit, errors.IsNotFound, func() error {
If we implement a timeout for components as well, we can just use that.

2024-11-19 12:52 UTC, jelemux approved these changes
LGTM!

2024-11-19 12:52 UTC, merged