Feature/1 initial structure
cloudogu/k8s-ces-setup pull request #2
Opened 2022-03-08 07:12 UTC by Subaro

Resolves #1

2022-03-10 09:43 UTC, Subaro commented
The failed check is for the SonarCube Quality Gates

2022-03-10 14:49 UTC, ppxl requested changes
Nice work, thank you for that! I have some findings which shouldn't take too long. Ofc I am open for discussing.

2022-03-10 14:49 UTC, ppxl commented on app/api/api.go
> +package api
does it really help to create an extra module for integration other APIs? Where is the benefit here? These two calls could dwell well in the calling `main.go` function.

2022-03-10 14:49 UTC, ppxl commented on app/config/config.go
> +	LogLevel            logrus.Level `yaml:"logLevel"`
Comments for public symbols! You get one, and you get one!
![grafik](https://user-images.githubusercontent.com/6781173/157677515-5316cf91-cd82-47c1-b219-e693a7b90ad8.png)

2022-03-10 14:49 UTC, ppxl commented on app/config/testdata/invalidConfig.yaml
> +This is not a valid yaml file!
Nice! :+1:

2022-03-10 14:49 UTC, ppxl commented on app/health/requestHandler.go
> +	c.JSON(200, response)
Always remember the good `http.StatusOK` semantics to avoid magic number :smile:

2022-03-10 14:49 UTC, ppxl commented on app/health/requestHandler.go
> +func newRequestHandler() *requestHandler {
is there more to come for this initializer? Otherwise it feels like YAGNI because it is so simple to call `&requestHandler{}` I mean it is not exported either...

2022-03-10 14:49 UTC, ppxl commented on app/setup/api.go
> +			_ = context.AbortWithError(http.StatusInternalServerError, err)
nicely called :+1:  Perhaps we later may want to avoid pushing every error to the client for security reasons.

2022-03-10 14:49 UTC, ppxl commented on app/setup/api.go
> +		return nil, fmt.Errorf("cannot load in cluster configuration; %w", err)
The semicolon strikes again! :fearful: :smile:

2022-03-10 14:49 UTC, ppxl commented on app/setup/api.go
> +		return nil, fmt.Errorf("cannot create kubernetes configuration; %w", err)
ditto

2022-03-10 14:49 UTC, ppxl commented on app/setup/executor.go
> +	ClientSet kubernetes.Interface `json:"clientSet"`
Rumor has it that we like documented exported symbols :smile: This might sound like nitpicking but a new reader will be thankful for a short abstract what (f. i.) a ClientSet _is_

2022-03-10 14:49 UTC, ppxl commented on app/setup/namespace_creation_step.go
> +type NamespaceCreator struct {
I think this struct is unnecessarily exported. We already have an interface for this in `executor.ExecutorStep`. The initializer just needs to return a ExecutorStep and we are good. I think the same goes for the fields. 

You already provided getters, so I guess this is an refactoring artefact?

2022-03-10 14:49 UTC, ppxl commented on app/setup/namespace_creation_step.go
> +func (n NamespaceCreator) createNamespace() error {
we have a pointer struct, why are the struct receivers not of type `*namespaceCreator`? IIRC all values would be copied on each method call.

2022-03-10 14:49 UTC, ppxl commented on app/setup/namespace_creation_step.go
> +func (n NamespaceCreator) PerformSetupStep() error {
Uuuhh the exported symbols and their doc comments. Don't led yourself mislead by the fact that the interface has proper comments. The implementation should describe their actual implementation behavior f. i.
```golang
// PerformSetupStep creates a namespace during setup execution.
```

2022-03-10 14:49 UTC, ppxl commented on docs/development/developers_guide_de.md
> +2. Die lokale Entwicklung am Setup kann mit `go run .` gestartet werden.
2.? This might be an refactoring artefact.

2022-03-10 14:49 UTC, ppxl commented on docs/operations/configuration_guide_de.md
> +# Konfigurationsanleitung
wow, in-depth docs :open_mouth:

2022-03-10 14:49 UTC, ppxl commented on docs/operations/configuration_guide_en.md
> +  ```yaml
Uuuuuh. That code fence doesn't belong here. Don't make it weird :laughing:

2022-03-10 14:49 UTC, ppxl commented on main.go
> +const SetupPort = 8080
this const can be de-exported because no other package uses it

2022-03-10 14:49 UTC, ppxl commented on app/config/config.go
> +var AppVersion Version = "0.0.0"
Why is here a different version variable than that from `main.go`? Shouldn't the version be consistent over the whole app?

2022-03-10 14:49 UTC, ppxl commented on main.go
> +	logrus.Debugf("Current Version: [%+v]", config.AppVersion)
Why is here a different version variable than that from the version above? Shouldn't the version be consistent over the whole app?

2022-03-10 14:49 UTC, ppxl commented on main.go
> +		panic(err)
I am not sure what to make of all these `panic`s in the main go. If we plan to test the main function this will be a PITA (similarly to `exit()`). I suggest encapsulating an exit call and hide the implementation behind an interface so tests will be possible again.

2022-03-10 14:49 UTC, ppxl commented on main.go
> +	logrus.SetFormatter(&logrus.TextFormatter{
I just wondered if we would receive ANSI formatting when we didn't want that (f. i. during reading `kubectl logs`) :grin:

2022-03-10 14:49 UTC, ppxl commented on main.go
> +	router.Use(ginlogrus.Logger(logrus.StandardLogger()), gin.Recovery())
oh, that's an idiom I don't recognize. What does it do?

2022-03-10 14:49 UTC, ppxl commented on release_args.sh
> +  k8sCesSetupYaml=k8s/k8s-ces-setup.yaml
I think we should make it a global variable because of all the occurrences here and the other function.

2022-03-11 06:41 UTC, Subaro commented on Dockerfile
> +COPY --chown=15000 --from=builder /workspace/target/k8s-ces-setup /k8s-ces-setup
The are no reasons for this.

2022-03-11 06:41 UTC, Subaro commented on Dockerfile
> +COPY --chown=15000 --from=builder /workspace/target/k8s-ces-setup /k8s-ces-setup
Accepted your proposal `--chown=15000:15000`

2022-03-11 07:06 UTC, Subaro commented on Dockerfile
> +COPY .git .git
Without the .git information the process does not fail but reports with:
```
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
```

2022-03-11 07:15 UTC, Subaro commented on Dockerfile
> +COPY .git .git
The reason for this is that we build the commit id into the binary with ldflags. Added the following comment:

`# Copy .git files as the build process builds the current commit id into the binary via ldflags`

2022-03-11 07:20 UTC, Subaro commented on Jenkinsfile
> +                                make 'compile'
I extracted `vet` as a separate stage.

2022-03-11 07:21 UTC, Subaro commented on Jenkinsfile
> +                    {
I agree on this point :)

2022-03-11 07:21 UTC, Subaro commented on Makefile
> +K8S_CLUSTER_ROOT=<your/path/to/k3ces>
To be Discussed

2022-03-11 07:22 UTC, Subaro commented on Makefile
> +IMAGE ?= cloudogu/${ARTIFACT_ID}:${VERSION}
Yes. Done.

2022-03-11 07:22 UTC, Subaro commented on Makefile
> +MAKEFILES_VERSION=5.0.0
Support the freshest `help` support. Feels really good.

2022-03-11 07:26 UTC, Subaro commented on Makefile
> +vet: $(STATIC_ANALYSIS_DIR) ## Run go vet against code.
I borrowed your proposal. However, make still does not report with `No work to be done`.

2022-03-11 07:27 UTC, Subaro commented on Makefile
> +${K8S_SETUP_DEV_RESOURCE_YAML}: # [not listed in help] Templates the deployment yaml with the latest image.
Done.

2022-03-11 07:28 UTC, Subaro commented on Makefile
> +.PHONY: clean-vendor
It was part of `ADDITIONAL_CLEAN`. I removed it entirely as it is part of the already present `make diss-clean`

2022-03-11 07:38 UTC, Subaro commented on app/api/api.go
> +		return fmt.Errorf("failed to setup 'health' api; %w", err)
I replaced every `; ` with `: `

2022-03-11 07:39 UTC, Subaro commented on Dockerfile
> +COPY Makefile Makefile
Done.

2022-03-11 07:39 UTC, Subaro commented on app/api/api.go
> +		return fmt.Errorf("failed to setup 'setup' api; %w", err)
Done.

2022-03-11 07:45 UTC, Subaro commented on app/api/api.go
> +package api
I moved the function into the main file.

2022-03-11 07:56 UTC, Subaro commented on app/health/requestHandler.go
> +	c.JSON(200, response)
Done:

2022-03-11 07:58 UTC, Subaro commented on app/health/requestHandler.go
> +func newRequestHandler() *requestHandler {
At the moment it does nothing more than that. I removed the `newRequestHandler` method. It can be introduced again if needed.

2022-03-11 08:00 UTC, Subaro commented on app/setup/api.go
> +			_ = context.AbortWithError(http.StatusInternalServerError, err)
The actual error message is not reported to the client. It is pushed to the error stack and only visible in the app's standard out.

2022-03-11 08:00 UTC, Subaro commented on app/setup/api.go
> +		return nil, fmt.Errorf("cannot load in cluster configuration; %w", err)
Done.

2022-03-11 08:00 UTC, Subaro commented on app/setup/api.go
> +		return nil, fmt.Errorf("cannot create kubernetes configuration; %w", err)
Done.

2022-03-11 08:06 UTC, Subaro commented on app/setup/executor.go
> +	ClientSet kubernetes.Interface `json:"clientSet"`
DOne.

2022-03-11 08:07 UTC, Subaro commented on app/setup/namespace_creation_step.go
> +type NamespaceCreator struct {
To be Discussed

2022-03-11 08:09 UTC, Subaro commented on app/setup/namespace_creation_step.go
> +func (n NamespaceCreator) createNamespace() error {
Good point. I changed the recieivers.

2022-03-11 08:11 UTC, Subaro commented on app/setup/namespace_creation_step.go
> +func (n NamespaceCreator) PerformSetupStep() error {
I did not know that this is a thing.

2022-03-11 08:12 UTC, Subaro commented on app/setup/namespace_creation_step.go
> +func (n NamespaceCreator) PerformSetupStep() error {
Done.

2022-03-11 08:13 UTC, Subaro commented on docs/development/developers_guide_de.md
> +2. Die lokale Entwicklung am Setup kann mit `go run .` gestartet werden.
Removed -> Done.

2022-03-11 08:15 UTC, Subaro commented on docs/operations/configuration_guide_en.md
> +  ```yaml
The downsides of C&P translations. You saw that well with your eagle eyes.

2022-03-11 08:15 UTC, Subaro commented on main.go
> +const SetupPort = 8080
Done.

2022-03-11 08:16 UTC, Subaro commented on app/config/config.go
> +var AppVersion Version = "0.0.0"
To Be Discussed.

2022-03-11 08:17 UTC, Subaro commented on main.go
> +	logrus.Debugf("Current Version: [%+v]", config.AppVersion)
Generally, the Version in the main file is set at compile time. Then it is passed to the configuration and from that moment accessible via the `config` package.

2022-03-11 08:19 UTC, Subaro commented on main.go
> +	logrus.SetFormatter(&logrus.TextFormatter{
To Be Discussed

2022-03-11 08:21 UTC, Subaro commented on main.go
> +	router.Use(ginlogrus.Logger(logrus.StandardLogger()), gin.Recovery())
You mean `ginlogrus.Logger` ? 

It generally bridges the connection between `gin` and `logrus`

2022-03-11 08:22 UTC, Subaro commented on release_args.sh
> +  k8sCesSetupYaml=k8s/k8s-ces-setup.yaml
Done.

2022-03-11 08:41 UTC, Subaro commented on main.go
> +		panic(err)
To Be Discused

2022-03-11 08:48 UTC, Subaro commented
Only sonar cube is failing

2022-03-11 14:38 UTC, ppxl commented on Jenkinsfile
> +                                make 'compile'
Nice!

2022-03-11 14:40 UTC, ppxl commented on app/setup/api.go
> +			_ = context.AbortWithError(http.StatusInternalServerError, err)
:+1:

2022-03-11 14:42 UTC, ppxl commented on main.go
> +	logrus.SetFormatter(&logrus.TextFormatter{
Discussed.

2022-03-11 14:42 UTC, ppxl approved these changes
LGTM

2022-03-11 14:44 UTC, ppxl commented
I am going to ignore the failed build check. The statical analysis mentions less than the desired ratio of code coverage which is okay for the setup skeleton. There are tests in decent amount and high quality, so this is nothing which discourages other developers over testing.

2022-03-11 14:44 UTC, merged