Feature/4 initialize cluster
cloudogu/k8s-ces-setup pull request #6
Opened 2022-04-21 12:55 UTC by ppxl

This PR changes the setup to install basic components (like dogu operator) and other necessities (like namespace, credentials) in order to prepare for a proper set-up procedure.

Resolve #4

2022-04-25 10:49 UTC, Subaro requested changes
The changes already look very good to me. Nice work especially with applying generic Kubernetes resources. There are still some minor changes that need to be assressed.

2022-04-25 10:49 UTC, Subaro commented on app/setup/api.go
> +			err2 := errors.Wrap(err, "error while setting up the setup API")
Use `fmt.Errorf` instead of `errors.Wrap`

2022-04-25 10:49 UTC, Subaro commented on app/setup/api.go
> +		return "", errors.Wrap(err, "failed to read current namespace from CREDENTIAL_SOURCE_NAMESPACE")
errors.Wrap is obsolete since go 1.13. You can use `fmt.Errorf` instead.

2022-04-25 10:49 UTC, Subaro commented on app/setup/api.go
> +// getEnvVar returns the namespace the operator should be watching for changes
The comment is from the `k8s-dogu-operator` :laughing:

2022-04-25 10:49 UTC, Subaro commented on app/setup/doguOperatorInstallerStep.go
> +		return err
Wrap error?

2022-04-25 10:49 UTC, Subaro commented on app/setup/doguOperatorInstallerStep.go
> +		return err
Wrap error?

2022-04-25 10:49 UTC, Subaro commented on app/setup/doguOperatorInstallerStep.go
> +	sections := splitYamlFileSections(fileContent)
Maybe the term `Document` would fit better than sections because the operation `---` is often referred to as document separator. 

` splitYamlFileDocuments`

2022-04-25 10:49 UTC, Subaro commented on app/setup/doguOperatorInstallerStep.go
> +	err = dois.applyYamlSections(sections)
Same as above. 

```suggestion
	err = dois.applyYamlDocuments(documents)
```

2022-04-25 10:49 UTC, Subaro commented on app/setup/doguOperatorInstallerStep_test.go
> +		expected := fmt.Sprintf(`apiVersion: rbac.authorization.k8s.io/v1
Instead of pasting the multiline content into the code, it is possible to put the expected files into a testdata directory. These can be embedded into the test. For an example see the dogu operator: https://github.com/cloudogu/k8s-dogu-operator/blob/a9439c93e4df20444fc46040a51420bc370a5b96/controllers/dogu_manager_test.go#L95

2022-04-25 10:49 UTC, Subaro commented on app/setup/etcdClientInstallerStep.go
> +		return err
Wrap error?

2022-04-25 10:49 UTC, Subaro commented on app/setup/etcdClientInstallerStep.go
> +		return err
Wrap error?

2022-04-25 10:49 UTC, Subaro commented on app/setup/etcdClientInstallerStep_internal_test.go
> +
empty line

2022-04-25 10:49 UTC, Subaro commented on app/setup/etcdServerInstallerStep.go
> +func (esis *etcdServerInstallerStep) applyYamlSections(sections [][]byte) error {
This method is very similar to the one in the dogu-operator installer step. Only the client is different. Maybe make the client a parameter instead of using a pointer reference and reuse the other one.

2022-04-25 10:49 UTC, Subaro commented on docs/development/setup_architecture_de.md
> +# Über die innere Architektur des Setups
Great documentation :+1:

2022-04-25 10:49 UTC, Subaro commented on app/core/apply.go
> +		return nil, errors.Wrap(err, "error while creating k8s apply client")
Use `fmt.Errorf`

2022-04-25 10:49 UTC, Subaro commented on app/core/apply.go
> +		return nil, errors.Wrap(err, "error while creating k8s apply client")
Use `fmt.Errorf`

2022-04-25 10:49 UTC, Subaro commented on app/core/apply.go
> +		return nil, err
Wrap error?

2022-04-25 10:49 UTC, Subaro commented on app/core/apply.go
> +		return err
Wrap error?

2022-04-25 10:49 UTC, Subaro commented on app/core/apply.go
> +		return err
Wrap error?

2022-04-25 10:49 UTC, Subaro commented on app/core/apply.go
> +	if err != nil {
:thinking: The variable `err` is not assigned after the last `nil`-check.

2022-04-25 12:36 UTC, ppxl commented on Makefile
> +VERSION=0.1.0-dev
yes, this is an development artifact and I shall revert it.

2022-04-25 12:37 UTC, ppxl commented on Makefile
> +	@cd ${K8S_CLUSTER_ROOT} && \
:smile:

2022-04-25 12:38 UTC, ppxl commented on Makefile
> +.PHONY: serve-local-yaml
Yes, I shall move it there

2022-04-25 12:47 UTC, ppxl commented on app/core/fileClient.go
> +	req.Header.Set("User-Agent", "Cloudia/"+dhc.version)
I chose to add a custom user agent in order to enable statistic tracking within the Cloudogu backend, basically for free. Why go with something rather mundane like ces-setup/1.2.3 when we can have ~~mozilla~~Cloudia/1.2.3? :wink:

2022-04-25 12:48 UTC, ppxl commented on app/core/fileClient.go
> +		return nil, err
yeah that makes sense

2022-04-25 12:49 UTC, ppxl commented on app/core/resourceError_test.go
> +		require.Implements(t, (*error)(nil), sut)
:bulb: :smile: Implementations and/or interfaces can change during implementation. With Golang's duck typing and these tests a misled refactoring can be uncovered. Totally nice!

2022-04-25 12:53 UTC, ppxl commented on app/setup/api.go
> +		clusterConfig, err := ctrl.GetConfig()
It seems, the `rest.Config` field in `context.SetupContext` is a refactoring artefact. I'd rather delete that one instead

2022-04-25 12:54 UTC, ppxl commented on app/setup/api.go
> +			err2 := errors.Wrap(err, "error while setting up the setup API")
Ah yes of course!

2022-04-25 12:55 UTC, ppxl commented on app/setup/api.go
> +		return "", errors.Wrap(err, "failed to read current namespace from CREDENTIAL_SOURCE_NAMESPACE")
will do

2022-04-25 12:56 UTC, ppxl commented on app/setup/api.go
> +// getEnvVar returns the namespace the operator should be watching for changes
impossibru! Yeah you got me and my lazy coding skills. I shall correct this

- [ ] done

2022-04-25 12:56 UTC, ppxl commented on app/core/resourceError_test.go
> +
- [ ] done

2022-04-25 12:57 UTC, ppxl commented on app/core/fileClient.go
> +// Get retrieves a file over HTTP returns its contents.
- [ ] done

2022-04-25 12:57 UTC, ppxl commented on Makefile
> +.PHONY: serve-local-yaml
- [ ] done

2022-04-25 13:01 UTC, ppxl commented on app/core/apply.go
> +		return nil, errors.Wrap(err, "error while creating k8s apply client")
- [ ] done

2022-04-25 13:01 UTC, ppxl commented on docs/development/setup_architecture_de.md
> +# Über die innere Architektur des Setups
Mercí :bow:

2022-04-25 13:01 UTC, ppxl commented on app/core/apply.go
> +		return nil, errors.Wrap(err, "error while creating k8s apply client")
- [ ] done

2022-04-25 13:03 UTC, ppxl commented on app/setup/etcdServerInstallerStep.go
> +func (esis *etcdServerInstallerStep) applyYamlSections(sections [][]byte) error {
I see what you try to achieve here. But I am not sure if that would be overengineering compared to any future changes to the installer steps. But I will look into it.

- [ ] done
- [ ] uh-oh, we need to talk

2022-04-25 13:03 UTC, ppxl commented on app/setup/etcdClientInstallerStep_internal_test.go
> +
- [ ] done

2022-04-25 13:06 UTC, ppxl commented on app/setup/doguOperatorInstallerStep.go
> +	err = dois.applyYamlSections(sections)
- [ ] done

2022-04-26 07:50 UTC, ppxl commented on app/context/setup_context.go
> +	K8sRestConfig rest.Config
Hmm, I shall think about it...
- [ ] done

2022-04-26 08:00 UTC, ppxl commented on app/core/apply.go
> +	if err != nil {
- [ ] done

2022-04-26 14:07 UTC, ppxl commented on app/core/fileClient.go
> +		return nil, err
Yeah the URL as additional info makes sense
- [X] done

2022-04-26 14:14 UTC, ppxl commented on app/core/apply.go
> +		return err
- [X] done

2022-04-26 14:14 UTC, ppxl commented on app/core/apply.go
> +		return err
- [X] done

2022-04-27 08:50 UTC, ppxl commented on app/context/setup_context.go
> +	K8sRestConfig rest.Config
I'd rather leave this as-is. The overhead does not seem that much mainly because the rest client will be instantiated exactly twice.

2022-04-27 12:15 UTC, Subaro commented on app/context/setup_context.go
> +	K8sRestConfig rest.Config
OK

2022-04-27 12:55 UTC, Subaro requested changes

2022-04-27 12:55 UTC, Subaro commented on docs/operations/installation_guide_de.md
> +kubectl create secret generic k8s-dogu-operator-dogu-registry --namespace=ecosystem --from-literal=username="your-ces-instance-id" --from-literal=password="your-ces-instance-password"
```suggestion
kubectl create secret generic k8s-dogu-operator-dogu-registry \
    --namespace=your-target-namespace \
    --from-literal=endpoint="https://dogu.cloudogu.com/api/v2/dogus" \
    --from-literal=username="your-ces-instance-id" \
    --from-literal=password="your-ces-instance-password"
```

2022-04-27 12:55 UTC, Subaro commented on docs/operations/installation_guide_de.md
> +kubectl create secret docker-registry k8s-dogu-operator-docker-registry --namespace=ecosystem --docker-server=registry.cloudogu.com --docker-username="your-ces-instance-id" --docker-password="your-ce
```suggestion
kubectl create secret docker-registry k8s-dogu-operator-docker-registry \
    --namespace=your-target-namespace \
    --docker-server=registry.cloudogu.com \
    --docker-username="your-ces-instance-id" \
    --docker-password="your-ces-instance-password"
```

2022-04-27 12:55 UTC, Subaro commented on docs/operations/installation_guide_en.md
> +  --from-literal=password="your-ces-instance-password"
```suggestion
kubectl create secret generic k8s-dogu-operator-dogu-registry \
  --namespace=your-target-namespace \
  --from-literal=endpoint="https://dogu.cloudogu.com/api/v2/dogus"
  --from-literal=username="your-ces-instance-id" \
  --from-literal=password="your-ces-instance-password"
```

2022-04-27 12:55 UTC, Subaro commented on main.go
> +	envVar, err := getEnvVar("POD_NAMESPACE")
Maybe this can be done directly in the configuration package?

2022-04-27 12:57 UTC, ppxl commented on docs/operations/installation_guide_de.md
> +kubectl create secret docker-registry k8s-dogu-operator-docker-registry --namespace=ecosystem --docker-server=registry.cloudogu.com --docker-username="your-ces-instance-id" --docker-password="your-ce
- [X] done

2022-04-27 14:05 UTC, ppxl commented on main.go
> +	envVar, err := getEnvVar("POD_NAMESPACE")
- [X] done

2022-04-27 14:10 UTC, Subaro requested changes

2022-04-27 14:10 UTC, Subaro commented on docs/operations/installation_guide_de.md
>  kubectl apply -f https://github.com/cloudogu/k8s-ces-setup/blob/develop/k8s/k8s-ces-setup.yaml
We need a small command to replace the target namespace in the `k8s-ces-setup`. Also, the target namespace should be provided when applying.

```suggestion
kubectl --namespace your-target-namespace apply -f https://github.com/cloudogu/k8s-ces-setup/blob/develop/k8s/k8s-ces-setup.yaml
```

2022-04-27 14:10 UTC, Subaro commented on docs/operations/installation_guide_en.md
>  kubectl apply -f https://github.com/cloudogu/k8s-ces-setup/blob/develop/k8s/k8s-ces-setup.yaml
We need a small command to replace the target namespace in the `k8s-ces-setup`. Also, the target namespace should be provided when applying.

```suggestion
kubectl --namespace your-target-namespace apply -f https://github.com/cloudogu/k8s-ces-setup/blob/develop/k8s/k8s-ces-setup.yaml
```

2022-04-27 14:29 UTC, ppxl commented on docs/operations/installation_guide_de.md
>  kubectl apply -f https://github.com/cloudogu/k8s-ces-setup/blob/develop/k8s/k8s-ces-setup.yaml
- [X] done

2022-04-27 14:30 UTC, ppxl commented on docs/operations/installation_guide_en.md
>  kubectl apply -f https://github.com/cloudogu/k8s-ces-setup/blob/develop/k8s/k8s-ces-setup.yaml
- [X] done

2022-04-27 14:31 UTC, ppxl commented on main.go
> +	return
- [X] done

2022-04-28 06:25 UTC, ppxl commented on main.go
> +	envVar, err := getEnvVar("POD_NAMESPACE")
- [X] done
-

2022-04-28 06:44 UTC, Subaro approved these changes

2022-04-28 06:44 UTC, Subaro commented on docs/operations/installation_guide_de.md
> +kubectl apply -f k8s-ces-setup.patched.yaml
```suggestion
kubectl --namespace your-target-namespace apply -f k8s-ces-setup.patched.yaml
```

2022-04-28 06:44 UTC, Subaro commented on docs/operations/installation_guide_en.md
> +kubectl apply -f k8s-ces-setup.patched.yaml
```suggestion
kubectl --namespace your-target-namespace apply -f k8s-ces-setup.patched.yaml
```

2022-04-28 06:45 UTC, Subaro requested changes

2022-04-28 06:45 UTC, Subaro commented on main.go
> +	return
Still redundant?

2022-04-28 07:05 UTC, Subaro approved these changes

2022-04-28 07:07 UTC, merged