Install cert-manager
cloudogu/k8s-ces-setup pull request #75
Opened 2023-10-13 13:37 UTC by nhinze23

Resolves #74

2023-10-18 13:53 UTC, meiserloh requested changes

2023-10-18 13:53 UTC, meiserloh commented on k8s/helm/values.yaml
> +#    helmRepositoryNamespace: k8s
hmmm... it feels a bit weird to me, that the component operator has it's own place in the yaml, to be identified directly, whereas the cert manager is in the components section and searched by name. Why not searching both by name or identify both directly? I think they should be handled the same way, shouldn't they?

2023-10-18 14:56 UTC, nhinze23 commented on k8s/helm/values.yaml
> +#    helmRepositoryNamespace: k8s
Lets talk about that. I thought about that too but this would create a breaking change..

2023-10-19 12:24 UTC, meiserloh commented on k8s/helm/values.yaml
> +#    helmRepositoryNamespace: k8s
decided with the team that it's okay like it is, because the component-operator is mandatory and the cert-manager is not.

2023-10-19 12:29 UTC, merged